name: CI - Lambda Identify

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt -t package && cp -R src/* package/
      - run: cd package && zip -r ../artifact.zip .
      - uses: actions/upload-artifact@v4
        with:
          name: lambda-identify
          path: artifact.zip
